// angular-to-do-list/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  imageSrc = '../assets/globo.png';
  constructor() { }

  ngOnInit(): void {
  }

}

<header class="app-header">
  <span class="app-header__logo">
    <img [src]="imageSrc" alt="imagem"/>
  </span>
  <span class="app-header__title">
      SIG - Sistema Integrado de Gestão
    </span>
</header>

// React-Todo/src/header/Header.js
import React from 'react'

import './Header.css'
import imagem from './img/globo.png'

const Header = () => (
    <header className="app-header">
        <div>
             <span className="app-header__logo">
            <img src={imagem} alt="imagem"/>
        </span>
            <span className="app-header__title">SIG - Sistema Integrado de Gestão</span>
        </div>
    </header>
)

export default Header
